package techstore.gui;

import java.util.ArrayList;
import techstore.SystemClass;
import techstore.models.ElectronicDevice;

public class ManagerFrame extends javax.swing.JFrame {

    ArrayList<ElectronicDevice> deviceList = new ArrayList<>();
    private int remainingSeconds = 300;

    public ManagerFrame() {
        initComponents();
        startSessionTimer();

        SystemClass.addDevice(deviceList);// Loads data from SystemClass
        // Sets initial visibility of components
        MessageofLabel.setVisible(false);
        SerialLabel.setVisible(false);
        SerialText.setVisible(false);
        DisplayTextArea.setVisible(false);
        ScrollPane.setVisible(false);
    }

    private void startSessionTimer() {
        // Initialize a timer that triggers every 1000ms (1 second)
        javax.swing.Timer countdownTimer = new javax.swing.Timer(1000, e -> {
            remainingSeconds--;

            // Calculate minutes and seconds to format as MM:SS
            int minutes = remainingSeconds / 60;
            int seconds = remainingSeconds % 60;
            String timeStr = String.format("%02d:%02d", minutes, seconds);

            // Update the timer label on the GUI
            LabelTimer.setText("SESSION TIMEOUT  " + timeStr);

            // If time is up, stop the timer and redirect to LoginFrame
            if (remainingSeconds <= 0) {
                ((javax.swing.Timer) e.getSource()).stop();
                javax.swing.JOptionPane.showMessageDialog(this, "Session expired! Redirecting to Login...");
                this.dispose();
                new LoginFrame().setVisible(true);
            }
        });

        countdownTimer.start(); // Start the countdown execution
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FunctionGroups = new javax.swing.ButtonGroup();
        ManagerPanel = new javax.swing.JPanel();
        DeviceTypeComboBox = new javax.swing.JComboBox<>();
        DeleteRbBtn = new javax.swing.JRadioButton();
        SearchRbBtn = new javax.swing.JRadioButton();
        DisplayRbBtn = new javax.swing.JRadioButton();
        AddRbBtn = new javax.swing.JRadioButton();
        ExitRbBtn = new javax.swing.JRadioButton();
        SerialLabel = new javax.swing.JLabel();
        SerialText = new javax.swing.JTextField();
        MessageofLabel = new javax.swing.JLabel();
        LabelTimer = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        DisplayTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeviceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Tablet", "Smartphone", "All Of Them" }));
        DeviceTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeviceTypeComboBoxActionPerformed(evt);
            }
        });

        FunctionGroups.add(DeleteRbBtn);
        DeleteRbBtn.setText("Product Delete");
        DeleteRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRbBtnActionPerformed(evt);
            }
        });

        FunctionGroups.add(SearchRbBtn);
        SearchRbBtn.setText("Product Search");
        SearchRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRbBtnActionPerformed(evt);
            }
        });

        FunctionGroups.add(DisplayRbBtn);
        DisplayRbBtn.setText("Product Display");
        DisplayRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayRbBtnActionPerformed(evt);
            }
        });

        FunctionGroups.add(AddRbBtn);
        AddRbBtn.setText("Product Add");
        AddRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRbBtnActionPerformed(evt);
            }
        });

        ExitRbBtn.setText("Exit");
        ExitRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitRbBtnActionPerformed(evt);
            }
        });

        SerialLabel.setText("Enter the serial number of the product :");

        SerialText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialTextActionPerformed(evt);
            }
        });

        LabelTimer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTimer.setForeground(new java.awt.Color(0, 0, 255));
        LabelTimer.setText(" ");

        ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        DisplayTextArea.setColumns(20);
        DisplayTextArea.setRows(5);
        ScrollPane.setViewportView(DisplayTextArea);

        javax.swing.GroupLayout ManagerPanelLayout = new javax.swing.GroupLayout(ManagerPanel);
        ManagerPanel.setLayout(ManagerPanelLayout);
        ManagerPanelLayout.setHorizontalGroup(
            ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddRbBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ExitRbBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeviceTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteRbBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchRbBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DisplayRbBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                .addGap(141, 141, 141)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addComponent(SerialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SerialText, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MessageofLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ManagerPanelLayout.setVerticalGroup(
            ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(DeviceTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SerialLabel)
                            .addComponent(SerialText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(AddRbBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteRbBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SearchRbBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DisplayRbBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExitRbBtn)
                        .addGap(314, 314, 314)
                        .addComponent(LabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(MessageofLabel)
                        .addGap(31, 31, 31)
                        .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(ManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRbBtnActionPerformed
        clearUI();
        // Prepares UI for the operation
        SerialLabel.setVisible(true);
        SerialText.setVisible(true);
        SerialText.setText("");

        MessageofLabel.setText("");
        MessageofLabel.setVisible(false);
        String serialNum = SerialText.getText().trim();
        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changes


    }//GEN-LAST:event_DeleteRbBtnActionPerformed

    private void SearchRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRbBtnActionPerformed
        clearUI();
        // Prepares UI for the operation
        SerialLabel.setVisible(true);
        SerialText.setVisible(true);
        SerialText.setText("");

        MessageofLabel.setText("");
        MessageofLabel.setVisible(false);
        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changes
    }//GEN-LAST:event_SearchRbBtnActionPerformed

    private void DisplayRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayRbBtnActionPerformed
        clearUI();
        SerialLabel.setVisible(false);
        SerialText.setVisible(false);
        MessageofLabel.setVisible(false);

        DisplayTextArea.setVisible(true);
        ScrollPane.setVisible(true);
        String selectedCategory = (String) DeviceTypeComboBox.getSelectedItem();
        StringBuilder filteredData = new StringBuilder();// Get the selected category from the dropdown menu

        // Iterate through the device list and filter objects based on their specific type using 'instanceof'
        for (techstore.models.ElectronicDevice device : deviceList) {
            if (selectedCategory.equals("Laptop") && device instanceof techstore.models.Laptop) {
                filteredData.append(device.toString()).append("\n----------------------------------------------\n");

            } else if (selectedCategory.equals("Tablet") && device instanceof techstore.models.Tablet) {
                filteredData.append(device.toString()).append("\n-------------------------------------------------\n");

            } else if (selectedCategory.equals("Smartphone") && device instanceof techstore.models.SmartPhone) {
                filteredData.append(device.toString()).append("\n-------------------------------------------------\n");

            } else if (selectedCategory.equals("All Of Them")) {
                filteredData.append(device.toString()).append("\n-------------------------------------------------\n");

            }
        }

        // Update the text area with the filtered results or show a 'not found' message
        if (filteredData.length() == 0) {
            DisplayTextArea.setText("No products found in the " + selectedCategory + " category.");
        } else {
            DisplayTextArea.setText(filteredData.toString());
        }
        // Append real-time stock amounts to the display
        DisplayTextArea.append("\n=== STOCK AMOUNT ===");

        if (selectedCategory.equals("Laptop") || selectedCategory.equals("All Of Them")) {
            DisplayTextArea.append("\nLaptops in Stock: " + techstore.SystemClass.getStockAmount_L());
        }
        if (selectedCategory.equals("Tablet") || selectedCategory.equals("All Of Them")) {
            DisplayTextArea.append("\nTablets in Stock: " + techstore.SystemClass.getStockAmount_T());
        }
        if (selectedCategory.equals("Smartphone") || selectedCategory.equals("All Of Them")) {
            DisplayTextArea.append("\nSmartphones in Stock: " + techstore.SystemClass.getStockAmount_S());
        }

        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changes


    }//GEN-LAST:event_DisplayRbBtnActionPerformed

    private void AddRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRbBtnActionPerformed
        clearUI();
        // Prepares UI for the operation
        SerialLabel.setVisible(true);
        SerialText.setVisible(true);
        SerialText.setText("");
        MessageofLabel.setText("");
        MessageofLabel.setVisible(true);
        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changes

    }//GEN-LAST:event_AddRbBtnActionPerformed

    private void DeviceTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeviceTypeComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DeviceTypeComboBoxActionPerformed

    private void SerialTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialTextActionPerformed
        String serialNum = SerialText.getText().trim();
        String selectedCategory = (String) DeviceTypeComboBox.getSelectedItem(); 
        clearUI();

        MessageofLabel.setVisible(true);
        // Validation: Check if the serial number field is empty
        if (serialNum.isEmpty()) {
            MessageofLabel.setText("Please enter a serial number!");
            return;
        }

        // Execution: Search for the device in the master list by serial number
        techstore.models.ElectronicDevice ex = SystemClass.searchDevice(deviceList, serialNum);
        boolean typeMatches = false;
        // Type Verification: Use 'instanceof' to check if the found object matches the selected category
        if (ex != null) {
            if (selectedCategory.equals("Laptop") && ex instanceof techstore.models.Laptop) {
                typeMatches = true;
            } else if (selectedCategory.equals("Tablet") && ex instanceof techstore.models.Tablet) {
                typeMatches = true;
            } else if (selectedCategory.equals("Smartphone") && ex instanceof techstore.models.SmartPhone) {
                typeMatches = true;
            } else if (selectedCategory.equals("All Of Them")) {
                typeMatches = true;
            }
        }
        // Logic Handling: Process operations if device exists and category is correct
        if (ex != null && typeMatches) {

            if (AddRbBtn.isSelected()) {
                SystemClass.addDeviceForManager(deviceList, ex);
                MessageofLabel.setText("Product added successfully ");
            } else if (DeleteRbBtn.isSelected()) {
                SystemClass.deleteDevice(deviceList, serialNum);
                MessageofLabel.setText("Product deleted successfully ");
            } else if (SearchRbBtn.isSelected()) {
                DisplayTextArea.setVisible(true);
                ScrollPane.setVisible(true);
                MessageofLabel.setText("Product found successfully ");
                DisplayTextArea.setText(SystemClass.searchDisplay(ex));
            }
        } else if (ex != null && !typeMatches) {
            // Error Handling: Serial number found but type mismatch
            MessageofLabel.setText("Serial " + serialNum + " found, but it is NOT a " + selectedCategory + "!");
        } else {
            // Error Handling: No device found with the provided serial number
            MessageofLabel.setText("No products matching the serial number were found.");
        }

    }//GEN-LAST:event_SerialTextActionPerformed

    private void ExitRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitRbBtnActionPerformed
        // TODO add your handling code here:
        clearUI();
        // If exit is selected, close current frame and open ExitFrame
        if (ExitRbBtn.isSelected()) {
            this.dispose();
            new ExitFrame().setVisible(true);// Show the final exit screen
        }
    }//GEN-LAST:event_ExitRbBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }

    private void clearUI() {
        /*
          Resets the visibility of all dynamic UI components to ensure a clean
          state before switching between different operations (Add, Delete,
          Search, Display).
         */

        ScrollPane.setVisible(false);// Hide the scroll pane that contains the inventory display
        // Hide input-related labels and text fields
        SerialLabel.setVisible(false);
        SerialText.setVisible(false);
        MessageofLabel.setVisible(false);
        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changes
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AddRbBtn;
    private javax.swing.JRadioButton DeleteRbBtn;
    private javax.swing.JComboBox<String> DeviceTypeComboBox;
    private javax.swing.JRadioButton DisplayRbBtn;
    private javax.swing.JTextArea DisplayTextArea;
    private javax.swing.JRadioButton ExitRbBtn;
    private javax.swing.ButtonGroup FunctionGroups;
    private javax.swing.JLabel LabelTimer;
    private javax.swing.JPanel ManagerPanel;
    private javax.swing.JLabel MessageofLabel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JRadioButton SearchRbBtn;
    private javax.swing.JLabel SerialLabel;
    private javax.swing.JTextField SerialText;
    // End of variables declaration//GEN-END:variables
}
