/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package techstore.gui;

/**
 *
 * @author Beyza
 */
public class ManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagerFrame
     */
    public ManagerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FunctionGroups = new javax.swing.ButtonGroup();
        ManagerPanel = new javax.swing.JPanel();
        DeviceTypeComboBox = new javax.swing.JComboBox<>();
        DeleteRbBtn = new javax.swing.JRadioButton();
        SearchRbBtn = new javax.swing.JRadioButton();
        DisplayRbBtn = new javax.swing.JRadioButton();
        AddRbBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DeviceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Tablet", "Smartphone" }));

        FunctionGroups.add(DeleteRbBtn);
        DeleteRbBtn.setText("Product Delete");
        DeleteRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRbBtnActionPerformed(evt);
            }
        });

        FunctionGroups.add(SearchRbBtn);
        SearchRbBtn.setText("Product Search");
        SearchRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRbBtnActionPerformed(evt);
            }
        });

        FunctionGroups.add(DisplayRbBtn);
        DisplayRbBtn.setText("Product Display");
        DisplayRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayRbBtnActionPerformed(evt);
            }
        });

        FunctionGroups.add(AddRbBtn);
        AddRbBtn.setText("Product Add");
        AddRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRbBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerPanelLayout = new javax.swing.GroupLayout(ManagerPanel);
        ManagerPanel.setLayout(ManagerPanelLayout);
        ManagerPanelLayout.setHorizontalGroup(
            ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DeviceTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteRbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchRbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DisplayRbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addComponent(AddRbBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(804, Short.MAX_VALUE))
        );
        ManagerPanelLayout.setVerticalGroup(
            ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(DeviceTypeComboBox)
                .addGap(27, 27, 27)
                .addComponent(AddRbBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteRbBtn)
                .addGap(18, 18, 18)
                .addComponent(SearchRbBtn)
                .addGap(18, 18, 18)
                .addComponent(DisplayRbBtn)
                .addGap(482, 482, 482))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ManagerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManagerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRbBtnActionPerformed
        // TODO add your handling code here:
        String item = DeviceTypeComboBox.getSelectedItem().toString();
        if(item=="Laptop"){
            //switch(){}

        }else if(item=="Tablet"){
            //switch{}
        }else{
            //switch{}
        }
    }//GEN-LAST:event_DeleteRbBtnActionPerformed

    private void SearchRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRbBtnActionPerformed
        // TODO add your handling code here:
        String item=DeviceTypeComboBox.getSelectedItem().toString();
        if(item=="Laptop"){
            //switch(){}

        }else if(item=="Tablet"){
            //switch{}
        }else{
            //switch{}
        }
    }//GEN-LAST:event_SearchRbBtnActionPerformed

    private void DisplayRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayRbBtnActionPerformed
        // TODO add your handling code here:
        String item=DeviceTypeComboBox.getSelectedItem().toString();
        if(item=="Laptop"){
            //switch(){}

        }else if(item=="Tablet"){
            //switch{}
        }else{
            //switch{}
        }
    }//GEN-LAST:event_DisplayRbBtnActionPerformed

    private void AddRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRbBtnActionPerformed
        // TODO add your handling code here:
        String item=DeviceTypeComboBox.getSelectedItem().toString();
        if(item=="Laptop"){
            //switch(){}

        }else if(item=="Tablet"){
            //switch{}
        }else{
            //switch{}
        }
    }//GEN-LAST:event_AddRbBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AddRbBtn;
    private javax.swing.JRadioButton DeleteRbBtn;
    private javax.swing.JComboBox<String> DeviceTypeComboBox;
    private javax.swing.JRadioButton DisplayRbBtn;
    private javax.swing.ButtonGroup FunctionGroups;
    private javax.swing.JPanel ManagerPanel;
    private javax.swing.JRadioButton SearchRbBtn;
    // End of variables declaration//GEN-END:variables
}
