package techstore.gui;

import java.util.ArrayList;
import techstore.SystemClass;
import techstore.models.ElectronicDevice;

public class PersonalFrame extends javax.swing.JFrame {

    ArrayList<ElectronicDevice> deviceList = new ArrayList<>();

    public PersonalFrame() {
        initComponents();
        // Loads data from SystemClass
        SystemClass.addDevice(deviceList);

        // Sets initial visibility of components
        MessageofLabel.setVisible(false);
        SerialLabel.setVisible(false);
        SerialText.setVisible(false);
        DisplayTextArea.setVisible(false);
        ScrollPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FunctionGroups = new javax.swing.ButtonGroup();
        PersonalPanel = new javax.swing.JPanel();
        DeviceTypeComboBox = new javax.swing.JComboBox<>();
        DeleteRbBtn = new javax.swing.JRadioButton();
        SearchRbBtn = new javax.swing.JRadioButton();
        DisplayRbBtn = new javax.swing.JRadioButton();
        SerialLabel = new javax.swing.JLabel();
        SerialText = new javax.swing.JTextField();
        MessageofLabel = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        DisplayTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeviceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Tablet", "Smartphone", "All Of Them" }));
        DeviceTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeviceTypeComboBoxActionPerformed(evt);
            }
        });

        FunctionGroups.add(DeleteRbBtn);
        DeleteRbBtn.setText("Product Delete");
        DeleteRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRbBtnActionPerformed(evt);
            }
        });

        FunctionGroups.add(SearchRbBtn);
        SearchRbBtn.setText("Product Search");
        SearchRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRbBtnActionPerformed(evt);
            }
        });

        FunctionGroups.add(DisplayRbBtn);
        DisplayRbBtn.setText("Product Display");
        DisplayRbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayRbBtnActionPerformed(evt);
            }
        });

        SerialLabel.setText("Enter the serial number of the product :");

        SerialText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialTextActionPerformed(evt);
            }
        });

        ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        DisplayTextArea.setColumns(20);
        DisplayTextArea.setRows(5);
        ScrollPane.setViewportView(DisplayTextArea);

        javax.swing.GroupLayout PersonalPanelLayout = new javax.swing.GroupLayout(PersonalPanel);
        PersonalPanel.setLayout(PersonalPanelLayout);
        PersonalPanelLayout.setHorizontalGroup(
            PersonalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PersonalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DeviceTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteRbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchRbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DisplayRbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGap(231, 231, 231)
                .addGroup(PersonalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonalPanelLayout.createSequentialGroup()
                        .addComponent(SerialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SerialText, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MessageofLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        PersonalPanelLayout.setVerticalGroup(
            PersonalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalPanelLayout.createSequentialGroup()
                .addGroup(PersonalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonalPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(DeviceTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PersonalPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(PersonalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SerialLabel)
                            .addComponent(SerialText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PersonalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonalPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(MessageofLabel))
                    .addGroup(PersonalPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(DeleteRbBtn)))
                .addGap(18, 18, 18)
                .addGroup(PersonalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonalPanelLayout.createSequentialGroup()
                        .addComponent(SearchRbBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DisplayRbBtn))
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        getContentPane().add(PersonalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRbBtnActionPerformed
        clearUI();
       // Prepares UI for the operation
        SerialLabel.setVisible(true);
        SerialText.setVisible(true);
        SerialText.setText("");

        MessageofLabel.setText("");
        MessageofLabel.setVisible(false);

        String serialNum = SerialText.getText().trim();
        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changes


    }//GEN-LAST:event_DeleteRbBtnActionPerformed

    private void SearchRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRbBtnActionPerformed
        clearUI();
        // Prepares UI for the operation
        SerialLabel.setVisible(true);
        SerialText.setVisible(true);
        SerialText.setText("");

        MessageofLabel.setText("");
        MessageofLabel.setVisible(false);
        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changes

    }//GEN-LAST:event_SearchRbBtnActionPerformed

    private void DisplayRbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayRbBtnActionPerformed
        clearUI();
// Calls SystemClass to display all devices
        SerialLabel.setVisible(false);
        SerialText.setVisible(false);

        MessageofLabel.setVisible(false);

        DisplayTextArea.setVisible(true);
        ScrollPane.setVisible(true);

        DisplayTextArea.setText(SystemClass.displayDevices(deviceList)
                + "\nThe number of Laptop: " + SystemClass.getStockAmount_L()
                + "\nThe number of Tablet: " + SystemClass.getStockAmount_T()
                + "\nThe number of Smartphone: " + SystemClass.getStockAmount_S());
        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changes


    }//GEN-LAST:event_DisplayRbBtnActionPerformed

    private void DeviceTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeviceTypeComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DeviceTypeComboBoxActionPerformed

    private void SerialTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialTextActionPerformed
        clearUI();
      // TODO add your handling code here:
        String serialNum = SerialText.getText().trim();
        if (DeleteRbBtn.isSelected()) {
            // Input Validation: Checks if input is empty
            if (serialNum.isEmpty()) {
                MessageofLabel.setText("Please enter a serial number!");
                return;
            }
            MessageofLabel.setVisible(true);
            // Search Logic: Checks if the device exists
            ElectronicDevice ex = SystemClass.searchDevice(deviceList, serialNum);
            if (ex != null) {
                // Delete Logic: Removes device via SystemClass
                SystemClass.deleteDevice(deviceList, serialNum);
                MessageofLabel.setText("Product deleted successfully");
            } else {
                MessageofLabel.setText("No products matching the serial number you entered were found.");
            }

        } else if (SearchRbBtn.isSelected()) {
            // Input Validation
            if (serialNum.isEmpty()) {
                MessageofLabel.setText("Please enter a serial number!");
                return;
            }
            MessageofLabel.setVisible(true);
            // Search and Display Logic
            ElectronicDevice ex = SystemClass.searchDevice(deviceList, serialNum);
            if (ex != null) {
                DisplayTextArea.setVisible(true);
                ScrollPane.setVisible(true);
                MessageofLabel.setText("Product successfully founded");
                // Shows specific device details
                DisplayTextArea.setText(SystemClass.searchDisplay(ex));
            } else {
                MessageofLabel.setText("No products matching the serial number you entered were found.");
            }

        }
        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changess

    }//GEN-LAST:event_SerialTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalFrame().setVisible(true);
            }
        });
    }

    private void clearUI() {
        /**
         * Resets the visibility of all dynamic UI components to ensure a clean
         * state before switching between different operations (Add, Delete,
         * Search, Display).
         */

        ScrollPane.setVisible(false);// Hide the scroll pane that contains the inventory display
        // Hide input-related labels and text fields
        SerialLabel.setVisible(false);
        SerialText.setVisible(false);
        this.revalidate();// Trigger the layout manager to recalculate the component hierarchy
        this.repaint();// Force a redraw of the frame to immediately reflect visibility changes
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DeleteRbBtn;
    private javax.swing.JComboBox<String> DeviceTypeComboBox;
    private javax.swing.JRadioButton DisplayRbBtn;
    private javax.swing.JTextArea DisplayTextArea;
    private javax.swing.ButtonGroup FunctionGroups;
    private javax.swing.JLabel MessageofLabel;
    private javax.swing.JPanel PersonalPanel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JRadioButton SearchRbBtn;
    private javax.swing.JLabel SerialLabel;
    private javax.swing.JTextField SerialText;
    // End of variables declaration//GEN-END:variables
}
